Algoritmo "Exercicio8"
// 8) Faça um algoritmo que calcule a área de um triângulo,
// considerando a fórmula area <- (base * altura) div 2.
// Utilize as variáveis area, base e altura e os operadores
// aritméticos de multiplicação e divisão.

Var
   base: real
   altura: real
   num: real
   total: inteiro

Inicio
      base <- 20
      altura <- 10
      num <- 2
      total <- (20 * 10) div 2
      escreval ("O Resultado da area é: ", total)


Fimalgoritmo