Algoritmo "Exercicio7"
// 7) Qual é o resultado das operações quando o algoritmo encontrar as
// seguintes linhas:
// a) Escreva ("mario" = "maria")
// b) Escreva (2 + 4 = 6)
// c) Escreva (10 - 4 > 7)
// d) Escreva ((2*3)>(3*2))
// e) Escreva (nao("a" > "A"))

Var

Inicio
      Escreval ("mario" = "maria")
      Escreval (2 + 4 = 6)
      Escreval (10 - 4 > 7)
      Escreval ((2*3)>(3*2))
      Escreval (nao("a" > "A"))
Fimalgoritmo