Algoritmo "Exercicio6)h"
// Calcule o valor de cada expressão abaixo e indique o tipo do resultado
// (inteiro ou real), onde b = 1 e c = 2:
// Letra H-35 div 6 - 2
Var
   //b, c : inteiro
   num1, num2, num3: inteiro
   resultado : inteiro

Inicio
      //b <- 1
      //c <- 2
      num1 <- 35
      num2 <- 6
      num3 <- 2
      resultado <- num1 div num2 - num3
      escreval("Resultado: ", resultado)
Fimalgoritmo