algoritmo "Exercicio5"
var
   Valor: inteiro
inicio
      Escreva(" Digite o  valor: ")
      leia (Valor)

      se Valor mod 2 = 0 entao
         escreva(" O numero", Valor, " é par")
      senao
         escreva(" O numero", Valor, " é impar")
      fimse
      
      se Valor >= 0 entao
         escreval(" E é Positivo")
      senao
         escreval(" E é Negativo")
      fimse
      
fimalgoritmo
