Algoritmo "Exercicio2"
// 2) Escreva um algoritmo que multiplique os valores de 2 matrizes 2 x 2.

Var
   matriz1: vetor [0..1, 0..1] de inteiro
   matriz2: vetor [0..1, 0..1] de inteiro
   l, c, l1, c1: inteiro
   
Inicio
      para l de 0 ate 1 passo 1 faca
      para c de 0 ate 1 passo 1 faca
      escreval("Informe o valor: ")
      leia (matriz1[l, c])
      fimpara
      fimpara


Fimalgoritmo