algoritmo "Exercicio 6"
// Função :
// Autor :
// Data : 03/04/2019
// Seção de Declarações 
var
   n,soma:inteiro
inicio
// Seção de Comandos
   escreval("Somaremos os valores digitados enquanto o valor for par.")
   escreval("No fim do algoritmo apresentaremos os valores da soma.")
   escreval

   enquanto (n mod 2 = 0) faca
   soma<-soma + n
   escreva("digite um numero: ")
   leia(n)
   fimenquanto

   escreva("o valor da soma é: ",soma)


fimalgoritmo
