Algoritmo "Exercicio2"
// 2) Escrever um algoritmo que leia dois valores inteiros
// distintos e informe qual é o maior.
Var
   a, b: inteiro

Inicio
      escreva("Informe o primeiro valor: ")
      leia(a)
      escreva("Informe o segundo valor: ")
      leia(b)
      se a > b entao
      escreva("O Valor" ,a," é maior que o valor",b)
      senao
      escreva("O Valor" ,b," é maior que o valor",a)
      fimse

Fimalgoritmo