algoritmo "Soma_Subtracao_A_e_B"
// Função : Somar e subtrair os valores de A e B.
// Autor : Priscilla Behnke
// Data : 26/03/2019
// Seção de Declarações 
var
A,B,C,D: inteiro

inicio
// Seção de Comandos 
A <-4
B <-3
C <- A+B
D <- A-B
ESCREVAL("O valor de A:", A)
ESCREVAL("O valor de B:", B)
ESCREVAL("O valor de C é (soma de A e B):", C)
ESCREVAL("O valor de D é (subtração de A e B):", D)
ESCREVAL(" ")
ESCREVAL("FIM ALGORITMO")

fimalgoritmo
