//Escreva um algoritmo que multiplique os valores de 2 matrizes 2 x 2.

algoritmo "Exercicio_02"
// Função:
// Autor: Priscilla Behnke
// Data : 20/04/2019
// Seção de Declarações 

var
M1,M2: inteiro
funcao multi(): inteiro

inicio
retorne M1 * M2
fimfuncao

inicio
M1 <- 2
M2 <- 2
ESCREVAL("Resultado da multiplicação das duas matrizes: ",multi())
M1 <- 4
M2 <- 4
ESCREVAL("Resultado da multiplicação das duas matrizes: ", multi())
ESCREVAL("OBS: Valor da Matriz A e B: 2. C e D:4")
fimalgoritmo
