algoritmo "Exercicio 8"
// Função :
// Autor :
// Data : 27/03/2019
// Seção de Declarações 
var
   base,altura,area:inteiro
inicio
// Seção de Comandos 
   escreval("vamos calcular a área de um triangulo")
   escreva("digite a base do triangulo: ")
   leia(base)
   escreva("digite a altura do triangulo: ")
   leia(altura)
   area <- (base * altura) div 2
   escreval("a área do triangulo é: ", area)
fimalgoritmo
