algoritmo "Exercicio 3"
// Função :
// Autor :
// Data : 27/03/2019
// Seção de Declarações 
var
   nome : caractere
   idade:inteiro
   salario:real
   masculino:logico
inicio
// Seção de Comandos 

   nome <- "Maria"
   idade <- 18
   salario <- 100,00
   masculino <- falso
   escreval("Nome: ", nome)
   escreval("Idade: ", idade)
   escreval("Salário: ", salario)
   escreval("É masculino?: ", masculino)


fimalgoritmo
