algoritmo "Exercicio 5"
// Função :
// Autor :
// Data : 27/03/2019
// Seção de Declarações 
var
   nome,endereco : caractere
   telefone,idade:inteiro

inicio
// Seção de Comandos 

   escreva("Nome: ")
   leia(nome)
   escreva("Telefone: ")
   leia(telefone)
   escreva("Endereço: ")
   leia(endereco)
   escreva("Idade: ")
   leia(idade)
   escreval
   escreval("Nome: ", nome)
   escreval("Telefone: ", telefone)
   escreval("Endereço: ", endereco)
   escreval("Idade: ", idade)


fimalgoritmo
