algoritmo "Exercicio 10"
// Função :
// Autor :
// Data : 27/03/2019
// Seção de Declarações 
var
   a,b,c:real
inicio
// Seção de Comandos 
   escreval("vamos trocar valores entre duas variaveis")
   escreva("digite o valor de A: ")
   leia(a)
   escreva("digite o valor de B: ")
   leia(b)
   escreval
   escreval("o valor de A é",a, " e o valor de B é",b)
   c <- b
   b <- a
   a <- c
   escreval("invertendo os valores...")
   escreval("o valor de A é",a, " e o valor de B é",b)
fimalgoritmo
