algoritmo 5
var
   nome : caractere
   idade : inteiro
   endereco : caractere
   telefone : inteiro

inicio
      Escreva("Digite o seu nome: ")
      leia(nome)
      Escreval(nome)
      Escreva("Digite sua idade: ")
      leia(idade)
      Escreval(idade)
      Escreva("Digite o seu endereço: ")
      leia(endereco)
      Escreval(endereco)
      Escreva("Digite o seu telefone: ")
      leia(telefone)
      Escreval(telefone)
fimalgoritmo

