algoritmo "Exercicio 2"
// Função :
// Autor :
// Data : 01/04/2019
// Seção de Declarações 
var
   n1,n2:inteiro
inicio
// Seção de Comandos 

   escreval("vamos analisar qual numero é maior entre duas possibilidades")
   escreva("digite o primeiro numero: ")
   leia(n1)
   escreva("digite o segundo numero: ")
   leia(n2)
   se n1 > n2 entao
      escreva(n1," é maior que ",n2)
   senao
      escreva(n2," é maior que ",n1)
   fimse

fimalgoritmo
