algoritmo "TipoDados"
var
      nome: caractere
      telefone: inteiro
      endereco: caractere
      idade: inteiro
Inicio
      nome <- "Marcelo Senna"
      telefone <- 991196857
      endereco <- "Rua Professor Othon Gama D'eça, 330"
      idade <- 42
      escreval("Nome: ", nome)
      escreval("telefone: ", telefone)
      escreval("endereco: ", endereco)
      escreval("idade: ", idade)
fimalgoritmo
