Algoritmo "Exercicio_8"
//Faça um algoritmo que calcule a área de um triângulo, considerando a fórmula
//area <- (base * altura) div 2. Utilize as variáveis area, base e altura e os
//operadores aritméticos de multiplicação e divisão.
Var
  area, altura, base: real

Inicio
    Escreva ("Digite base: ")
    Leia(base)
    Escreva ("Digite Altura: ")
    Leia(altura)
    area <- (base * altura) / 2
    limpatela
    Escreva ("A área do triângulo é: ", area)


Fimalgoritmo