algoritmo "Notas"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
//Obtendo 2 notas do teclado, calcule a média delas e apresente a média na tela
var
     nota1, nota2, media: Real
Inicio
      Escreva("Digite a nota1: ")
      Leia (nota1)
      Escreva("digite a nota2: ")
      Leia (nota2)
      media <- (nota1 + nota2) / 2
      Escreva ("A media das notas é: ", media)
fimalgoritmo
