Algoritmo "To ficando bom"
// 8) Faça um algoritmo que calcule a área de um triângulo, considerando a
// fórmula area <- (base * altura) div 2. Utilize as variáveis area, base e
// altura e os operadores aritméticos de multiplicação e divisão.

Var
   base, altura, num1, total: inteiro

Inicio
    base <- 10
    altura <- 15
    num1 <- 2
    total <- (base * altura) div num1
    escreval ("area do triangulo: ", total)

Fimalgoritmo