Algoritmo "Exercicio2"
// 2) Faça um algoritmo que leia um número e mostre a fatorial
// desse número. (N * N - 1 * N - 2 * ... * N - (N-1))
Var
   n, resultado, fatorial: inteiro

Inicio
      escreva("Digite um numero: ")
      leia(n)
      fatorial <- 1
      para resultado de n ate 1 passo -1 faca
      fatorial <- fatorial * resultado
      fimpara
      escreva("Fatorial: ", fatorial)

Fimalgoritmo