algoritmo "Exercicio_2"
//Escrever um algoritmo que leia dois valores inteiros distintos e informe
//qual é o maior.
var
    num1, num2: inteiro

inicio
      Escreva("Digite o número:")
      Leia(num1)
      Escreva("Digite o número:")
      Leia(num2)
      se num1 > num2 entao
         Escreva ( "O número maior é:" ,num1)
      senao
         Escreva ( "O número maior é:" ,num2)
      fimse
fimalgoritmo

