Algoritmo "Exercicio1"
// 1) Escrever um algoritmo que possua um vetor inteiro de 5 posições
// com os dados fornecidos pelo usuário. Após preencher o vetor
// apresentar a posição e o valor preenchido na posição.

Var
   i: inteiro
   valor: vetor [0..4] de inteiro

Inicio
      para i de 0 ate 4 passo 1 faca
      escreva("Digite o Valor: ")
      leia(valor[i])
      fimpara
      para i de 0 ate 4 passo 1 faca
      escreval(valor[i])
      fimpara

Fimalgoritmo