Algoritmo "Comecou a avacalhar"
// Calcule o valor de cada expressão abaixo e indique o tipo do resultado
//(inteiro ou real), onde b = 1 e c = 2:
// D) 2*(5/20) + 30/(15*2)
Var
 b, c: inteiro
 num1, num2, num3, num4, num5: inteiro
 resultado: real

Inicio
    b <- 1
    c <- 2
    num1 <- 2
    num2 <- 5
    num3 <- 20
    num4 <- 30
    num5 <- 15
    resultado <- num1 * (num2 / num3) +  num4 / (num5 * num1)
    escreval ("resultado da espressao é: ", resultado)
    


Fimalgoritmo