Algoritmo "Comecou a avacalhar"
// Calcule o valor de cada expressão abaixo e indique o tipo do resultado
//(inteiro ou real), onde b = 1 e c = 2:
// e) 23 div 4
Var
 b, c: inteiro
 num1, num2, num3, num4, num5: inteiro
 resultado: inteiro

Inicio
    b <- 1
    c <- 2
    num1 <- 23
    num2 <- 4
    resultado <- num1 div num2
    escreval ("resultado da espressao é: ", resultado)
    


Fimalgoritmo