Algoritmo "Comecou a avacalhar"
// Calcule o valor de cada expressão abaixo e indique o tipo do resultado
//(inteiro ou real), onde b = 1 e c = 2:
// H) 35 div 6 - 2
Var
 b, c: inteiro
 num1, num2, num3, num4, num5: inteiro
 resultado: inteiro

Inicio
    b <- 1
    c <- 2
    num1 <- 35
    num2 <- 6
    resultado <- num1 div (num2 - c)
    escreval ("resultado da espressao é: ", resultado)
    


Fimalgoritmo