Algoritmo "Comecou a avacalhar"
// 7) Qual é o resultado das operações quando o algoritmo encontrar as
// seguintes linhas
// a) Escreva ("mario" = "maria")
// b) Escreva (2 + 4 = 6)
// c) Escreva (10 - 4 > 7)
// d) Escreva ((2*3)>(3*2))
// e) Escreva (nao("a" > "A"))

Var

Inicio
    escreval ("mario" = "maria")
    escreval (2 + 4 = 6)
    escreval (10 - 4 > 7)
    escreval ((2*3)>(3*2))
    escreval (nao("a" > "A"))

Fimalgoritmo