algoritmo "Exercicio1"
var
   Valor1, Valor2: Inteiro
inicio
      Escreva(" Digite o primeiro valor: ")
      leia (Valor1)
      Escreva("Digite o segundo valor: ")
      Leia(Valor2)

      se Valor1 > Valor2 entao
      escreval("A diferença entre o primeiro e o segundo valor é", (Valor1-Valor2))
      senao
      escreval("A diferença entre o segundo e o primeiro valor é", (Valor2-Valor1))
      fimse
fimalgoritmo

