//Escreva um algoritmo de um calculadora, que irá solicitar ao usuário qual operação deseja realizar. De acordo com a operação desejada será chamado um
//procedimento diferente que obterá 2 valores, realizará o cálculo da operação informado e escreverá o resultado.

algoritmo "Exercicio_02"
// Função :
// Autor :
// Data : 02/05/2019
// Seção de Declarações 
var

inicio
// Seção de Comandos 
fimalgoritmo
