algoritmo "TiposDados"
var
   nome : caractere
   idade : inteiro
   cidade : caractere
   renda: real
   tem_filhos : logico
inicio
      nome <- "João"
      idade <- 30
      cidade <- "Floripa"
      renda <- 50,05
      tem_filhos <- falso
      escreval("Nome: ", nome)
      escreval("Idade: ", idade)
      escreval("cidade: ", cidade)
      escreval("renda: ", renda)
      escreval("Tem filhos?: ", tem_filhos)
fimalgoritmo

