algoritmo "Exercicio6"
var
   b, c: inteiro
   a1: real
   a2: real
   a3: real
   a4: real
   a5: inteiro
   a6: inteiro
   a7: inteiro
   a8: inteiro
inicio
      b <- 1
      c <- 2
      a1 <- (20 - 15)/(2 * b)
      a2 <- 20 - 15/(2 * c)
      a3 <- 2*5/20 + 30/15*2
      a4 <- 2*(5/20) + 30/(15*2)
      a5 <- 23 div 4
      a6 <- 23 mod 4
      a7 <- 35 div 6 + 2
      a8 <- 35 div 6 - 2
      
      
fimalgoritmo
